### ISSUE TITLE
Deployment file

### ISSUE THREAD

**Issue by doggiedoggie1026** [microsoft/CogACT#3]
Thank you for providing the open source code and detailed documentation. 
We noticed that the documentation does not seem to mention the deployment file, such as deploying the fine-tuned model to other types of manipulators. Is there any documentation for reference?

**Comment by arnoldland** [comment]
Thank you for your interest. For deployment, please refer to the inference file [sim_cogact/cogact_policy.py](https://github.com/microsoft/CogACT/blob/main/sim_cogact/cogact_policy.py) within the simulator. Additionally, we will provide a separate file to demonstrate how to serve a fine-tuned model for your reference. Welcome to try it out!

**Comment by arnoldland** [comment]
Please refer to [scripts/deploy.py](https://github.com/microsoft/CogACT/blob/main/scripts/deploy.py) and the updated README.md for deployment.

**Comment by doggiedoggie1026** [comment]
Thanks! I'll check for updates now!
